"""
Django settings for chico_healthcare project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

SECRET_KEY = "django-insecure-$zx1%u+tgkp---8n#c7l(%b(w__^_@v57a&vl-m$1b7u4gm=lj"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'users',
    'patient',
    'insurance_provider',
    'doctor',
    'system',
    'navbars',
    'homepage',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'chico_healthcare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chico_healthcare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'my_django_db',
        'USER': 'my_django_user',
        'PASSWORD': 'patilom2114',
        'HOST': '34.135.75.188',
        'PORT': 5432
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

STATIC_DIR = os.path.join(BASE_DIR, "static")


STATICFILES_DIRS = [ STATIC_DIR ]

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# STATICFILES_DIRS = [
#     # os.path.join(BASE_DIR, 'static'),
#     os.path.join(BASE_DIR, 'users', 'static/'),
#     os.path.join(BASE_DIR, 'patient', 'static/patient'),
#     os.path.join(BASE_DIR, 'doctor', 'static/doctor'),
#     os.path.join(BASE_DIR, 'insurance_provider', 'static/insurance_provider'),
# ]





DEFAULT_FROM_EMAIL = 'patilom2114@example.com'

# Use the SendGrid API backend for sending email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Set the SendGrid API key as the email password
EMAIL_HOST_PASSWORD = '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'

CORS_ALLOWED_ORIGINS = [
    "https://my-service-222rg7v33a-uc.a.run.app",
    "https://healthinessease.com"
]

CORS_ORIGIN_WHITELIST = [
    'https://my-service-222rg7v33a-uc.a.run.app',
    "https://healthinessease.com"
    # add any other origins that need to be whitelisted
]

CSRF_TRUSTED_ORIGINS = [
    "https://my-service-222rg7v33a-uc.a.run.app",
    "https://healthinessease.com"
]

