# Generated by Django 4.1.7 on 2023-04-18 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 18, 5, 59, 13, 118357, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
