# Generated by Django 4.1.7 on 2023-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=100, verbose_name='Name')),
                ('validity', models.IntegerField(verbose_name='Valid till')),
                ('coverage', models.IntegerField(verbose_name='Coverage')),
            ],
        ),
    ]
