# Generated by Django 4.1.7 on 2023-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
