# Generated by Django 4.1.7 on 2023-04-29 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_provider', '0003_insurancedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepurchased', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('insuranceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurance_provider.insurancedetails')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
