# Generated by Django 4.1.7 on 2023-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_provider', '0004_insurancepurchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepurchasehistory',
            name='datepurchased',
            field=models.DateField(),
        ),
    ]
