# Generated by Django 4.1.7 on 2023-05-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_provider', '0005_alter_insurancepurchasehistory_datepurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepurchasehistory',
            name='claim',
            field=models.BooleanField(default=False),
        ),
    ]
