# Generated by Django 4.1.7 on 2023-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_provider', '0006_insurancepurchasehistory_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepurchasehistory',
            name='claim',
            field=models.CharField(default='notclaimed', max_length=50),
        ),
    ]
