# Generated by Django 4.1.7 on 2023-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_provider', '0007_alter_insurancepurchasehistory_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepurchasehistory',
            name='cancellationreason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
